name: Deploy Storeroom

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥Code
        uses: actions/checkout@v4

      - name: 🏗Vite CSS/JS
        run: |
          npm install
          npm run build

      - name: 🐘 Composer
        run: |
          composer install --no-dev --optimize-autoloader

      # Récupérer l'IP publique du runner GitHub
      - name: Get runner's public IP
        id: ip
        uses: haythem/public-ip@v1.3

      # Ajouter l'IP du runner à la whitelist SSH de o2Switch
      - name: Whitelist IP on hosting & delete github old ones (o2switch)
        shell: bash
        run: |
          ENDPOINT='frontend/o2switch/o2switch-ssh-whitelist/index.live.php'
    
          echo "Get actual whitelisted IPs..."
          RESPONSE=$(curl -sX GET "https://${{ secrets.SSH_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=list")
          echo "Response: $RESPONSE"
          UNIQUE_IPS=$(echo "$RESPONSE" | jq -r '.data.list[] | .address' | sort -u)
    
          for address in $UNIQUE_IPS; do
            echo "Delete this github IP: $address (in & out)"
            curl -sX GET "https://${{ secrets.SSH_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=remove&address=$address&direction=in&port=22" | jq
            sleep 3
            curl -sX GET "https://${{ secrets.SSH_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=remove&address=$address&direction=out&port=22" | jq
            sleep 3
          done
          echo "All non-whitelisted IPs deleted!"
    
          echo "Attempt to whitelist IP..."
          curl -sX POST -d 'whitelist[address]=${{ steps.ip.outputs.ipv4 }}' -d 'whitelist[port]=22' "https://${{ secrets.SSH_USER }}:${{ secrets.URL_ENCODED_PASSWORD }}@${{ secrets.SSH_HOST }}:2083/$ENDPOINT?r=add" | jq
          echo "Waiting 10 seconds for o2switch firewall to update..."
          sleep 10

      - name: 'Deploy on master branch'
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete-after"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: '22'
          TARGET: ${{ secrets.REMOTE_PATH }}
          EXCLUDE: "./.git*, ./.env, /node_modules/, ./web/app/uploads/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT