name: Deploy Storeroom

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥Code
        uses: actions/checkout@v4

      - name: 🏗Vite CSS/JS
        run: |
          npm install
          npm run build

      - name: 🐘 Composer
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Github IP
        id: ip
        run: echo "ipv4=$(curl -s https://ifconfig.me)" >> $GITHUB_OUTPUT

      - name: Open Firewall
        run: |
          curl -X POST "https://api.o2switch.fr/v1/firewall/ip/allow" \
          -H "Authorization: Bearer ${{ secrets.O2_API_TOKEN }}" \
          -d "ip=${{ steps.ip.outputs.ipv4 }}"
          echo "Attente de l'ouverture du pare-feu..."
          sleep 15

      - name: 🚀 Deploy
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: >-
            -avzr --delete
            --exclude='.git*' 
            --exclude='.env' 
            --exclude='node_modules' 
            --exclude='/web/app/uploads' 
            --exclude='/web/app/cache'
            -e 'ssh -p 22 -o StrictHostKeyChecking=no'
          path: .
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}